INSERT INTO "key_books" VALUES (1, 'Бытие', 'OT', 0);
INSERT INTO "key_books" VALUES (2, 'Исход', 'OT', 0);
INSERT INTO "key_books" VALUES (3, 'Левит', 'OT', 0);
INSERT INTO "key_books" VALUES (4, 'Числа', 'OT', 0);
INSERT INTO "key_books" VALUES (5, 'Второзаконие', 'OT', 0);
INSERT INTO "key_books" VALUES (6, 'Книга Иисуса Навина', 'OT', 0);
INSERT INTO "key_books" VALUES (7, 'Книга Судей израилевых', 'OT', 0);
INSERT INTO "key_books" VALUES (8, 'Книга Руфи', 'OT', 0);
INSERT INTO "key_books" VALUES (9, 'Первая книга Царств', 'OT', 0);
INSERT INTO "key_books" VALUES (10, 'Вторая книга Царств', 'OT', 0);
INSERT INTO "key_books" VALUES (11, 'Третья книга Царств', 'OT', 0);
INSERT INTO "key_books" VALUES (12, 'Четвертая книга Царств', 'OT', 0);
INSERT INTO "key_books" VALUES (13, 'Первая книга Паралипоменон', 'OT', 0);
INSERT INTO "key_books" VALUES (14, 'Вторая книга Паралипоменон', 'OT', 0);
INSERT INTO "key_books" VALUES (15, 'Первая книга Ездры', 'OT', 0);
INSERT INTO "key_books" VALUES (16, 'Книга Неемии', 'OT', 0);
INSERT INTO "key_books" VALUES (17, 'Вторая книга Ездры', 'OT', 0);
INSERT INTO "key_books" VALUES (18, 'Книга Товита', 'OT', 0);
INSERT INTO "key_books" VALUES (19, 'Книга Иудифи', 'OT', 0);
INSERT INTO "key_books" VALUES (20, 'Книга Есфири', 'OT', 0);
INSERT INTO "key_books" VALUES (21, 'Книга Иова', 'OT', 0);
INSERT INTO "key_books" VALUES (22, 'Псалтирь', 'OT', 0);
INSERT INTO "key_books" VALUES (23, 'Притчи Соломона', 'OT', 0);
INSERT INTO "key_books" VALUES (24, 'Книга Екклезиаста', 'OT', 0);
INSERT INTO "key_books" VALUES (25, 'Песнь песней Соломона', 'OT', 0);
INSERT INTO "key_books" VALUES (26, 'Книга Премудрости Соломона', 'OT', 0);
INSERT INTO "key_books" VALUES (27, 'Книга Премудрости Иисуса, сына Сирахова', 'OT', 0);
INSERT INTO "key_books" VALUES (28, 'Книга пророка Исаии', 'OT', 0);
INSERT INTO "key_books" VALUES (29, 'Книга пророка Иеремии', 'OT', 0);
INSERT INTO "key_books" VALUES (30, 'Плач Иеремии', 'OT', 0);
INSERT INTO "key_books" VALUES (31, 'Послание Иеремии', 'OT', 0);
INSERT INTO "key_books" VALUES (32, 'Книга пророка Варуха', 'OT', 0);
INSERT INTO "key_books" VALUES (33, 'Книга пророка Иезекииля', 'OT', 0);
INSERT INTO "key_books" VALUES (34, 'Книга пророка Даниила', 'OT', 0);
INSERT INTO "key_books" VALUES (35, 'Книга пророка Осии', 'OT', 0);
INSERT INTO "key_books" VALUES (36, 'Книга пророка Иоиля', 'OT', 0);
INSERT INTO "key_books" VALUES (37, 'Книга пророка Амоса', 'OT', 0);
INSERT INTO "key_books" VALUES (38, 'Книга пророка Авдия', 'OT', 0);
INSERT INTO "key_books" VALUES (39, 'Книга пророка Ионы', 'OT', 0);
INSERT INTO "key_books" VALUES (40, 'Книга пророка Михея', 'OT', 0);
INSERT INTO "key_books" VALUES (41, 'Книга пророка Наума', 'OT', 0);
INSERT INTO "key_books" VALUES (42, 'Книга пророка Аввакума', 'OT', 0);
INSERT INTO "key_books" VALUES (43, 'Книга пророка Софонии', 'OT', 0);
INSERT INTO "key_books" VALUES (44, 'Книга пророка Аггея', 'OT', 0);
INSERT INTO "key_books" VALUES (45, 'Книга пророка Захарии', 'OT', 0);
INSERT INTO "key_books" VALUES (46, 'Книга пророка Малахии', 'OT', 0);
INSERT INTO "key_books" VALUES (47, 'Первая книга Маккавейская', 'OT', 0);
INSERT INTO "key_books" VALUES (48, 'Вторая книга Маккавейская', 'OT', 0);
INSERT INTO "key_books" VALUES (49, 'Третья книга Маккавейская', 'OT', 0);
INSERT INTO "key_books" VALUES (50, 'Третья книга Ездры', 'OT', 0);
INSERT INTO "key_books" VALUES (51, 'От Матфея святое благовествование', 'NT', 0);
INSERT INTO "key_books" VALUES (52, 'От Марка святое благовествование', 'NT', 0);
INSERT INTO "key_books" VALUES (53, 'От Луки святое благовествование', 'NT', 0);
INSERT INTO "key_books" VALUES (54, 'От Иоанна святое благовествование', 'NT', 0);
INSERT INTO "key_books" VALUES (55, 'Деяния святых апостолов', 'NT', 0);
INSERT INTO "key_books" VALUES (56, 'Соборное послание святого апостола Иакова', 'NT', 0);
INSERT INTO "key_books" VALUES (57, 'Первое соборное послание святого апостола Петра', 'NT', 0);
INSERT INTO "key_books" VALUES (58, 'Второе соборное послание святого апостола Петра', 'NT', 0);
INSERT INTO "key_books" VALUES (59, 'Первое соборное послание святого апостола Иоанна', 'NT', 0);
INSERT INTO "key_books" VALUES (60, 'Второе соборное послание святого апостола Иоанна', 'NT', 0);
INSERT INTO "key_books" VALUES (61, 'Третье соборное послание святого апостола Иоанна', 'NT', 0);
INSERT INTO "key_books" VALUES (62, 'Соборное послание святого апостола Иуды', 'NT', 0);
INSERT INTO "key_books" VALUES (63, 'Послание к Римлянам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (64, 'Первое послание к Коринфянам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (65, 'Второе послание к Коринфянам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (66, 'Послание к Галатам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (67, 'Послание к Ефесянам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (68, 'Послание к Филиппийцам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (69, 'Послание к Колоссянам святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (70, 'Первое послание к Фессалоникийцам (Солунянам) святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (71, 'Второе послание к Фессалоникийцам (Солунянам) святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (72, 'Первое послание к Тимофею святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (73, 'Второе послание к Тимофею святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (74, 'Послание к Титу святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (75, 'Послание к Филимону святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (76, 'Послание к Евреям святого апостола Павла', 'NT', 0);
INSERT INTO "key_books" VALUES (77, 'Откровение святого Иоанна Богослова', 'NT', 0);
